<template>
  <v-container>
    <h1>エンジニアの一覧</h1>
    <section>
      <h2>技術スタック</h2>
      <section>
        <h3>フロントエンド</h3>
        <section>
          <h4>HTML / CSS</h4>
        </section>
        <section>
          <h4>JavaScript / TypeScript</h4>
          <p>色々書く</p>
          <div>
            <div>
              <h5>Vue / Nuxt</h5>
              <p>色々書く</p>
            </div>
            <div>
              <h5>React / Next</h5>
              <p>色々書く</p>
            </div>
          </div>
        </section>
      </section>
      <section>
        <h3>サーバーサイド</h3>
        <section>
          <h4>PHP</h4>
          <p>色々書く</p>
        </section>
      </section>
      <section>
        <h3>インフラ</h3>
        <section>
          <h4>AWS</h4>
          <p>色々書く</p>
        </section>
        <section>
          <h4>Docker</h4>
          <p>色々書く</p>
        </section>
        <section>
          <h4>DB</h4>
          <p>色々書く</p>
        </section>
      </section>
      <section>
        <h3>モバイル</h3>
        <section>
          <h4>Swift</h4>
          <p>色々書く</p>
        </section>
        <section>
          <h4>Kotlin</h4>
          <p>色々書く</p>
        </section>
      </section>
      <section>
        <h3>その他</h3>
        <section>
          <h4>サンプル</h4>
          <p>色々書く</p>
        </section>
      </section>
    </section>
  </v-container>
</template>
